# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.provision :shell, path: "config_script.sh"
  config.vm.provision :shell, path: "test_script.sh"
end
